### ISSUE TITLE
2D Tracking Testing中遇到的问题

### ISSUE THREAD

**Issue by ZhouAugustus** [GaoangW/TNT#15]
tracklet_utils_3c.py参数：
det_path = '/home/ma-user/modelarts/inputs/data_url_0/det.txt'#MOT17-02-FRCNN/det/det.txt
gt_path = ''
img_folder = '/home/ma-user/modelarts/inputs/data_url_0/img1'#MOT17-02-FRCNN\img1
triplet_model = '/home/ma-user/modelarts/inputs/data_url_0/model/20211201-122017/'#train_tripletloss的结果
seq_model = '/home/ma-user/modelarts/inputs/data_url_0/model/model/model.ckpt'#train_cnn_trajectory_2d.py的结果
错误日志：
> /home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py(762)comb_cost()
-> comb_fea_mat[cnt,4:,t1_min-t_min:t1_max-t_min+1,0] = np.transpose(tracklet_mat['appearance_fea_mat'][cand_idx,2:])
(Pdb) 
Traceback (most recent call last):
  File "/home/ma-user/modelarts/user-job-dir/code/TC_tracker.py", line 35, in <module>
    track_struct = tracklet_utils_3c.TC_tracker()
  File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 2739, in TC_tracker
    batch_mask_2, batch_Y, keep_prob, y_conv)
  File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 1774, in tracklet_clustering
    batch_mask_2, batch_Y, keep_prob, y_conv)
  File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 1114, in get_assign_cost
    batch_Y, keep_prob, y_conv)
  File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 762, in comb_cost
    comb_fea_mat[cnt,4:,t1_min-t_min:t1_max-t_min+1,0] = np.transpose(tracklet_mat['appearance_fea_mat'][cand_idx,2:])
  File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 762, in comb_cost
    comb_fea_mat[cnt,4:,t1_min-t_min:t1_max-t_min+1,0] = np.transpose(tracklet_mat['appearance_fea_mat'][cand_idx,2:])
  File "/home/ma-user/anaconda/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/ma-user/anaconda/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
问题：我做错了什么吗？为什么会报这个错？

**Comment by ZhouAugustus** [comment]
> tracklet_utils_3c.py参数： det_path = '/home/ma-user/modelarts/inputs/data_url_0/det.txt'#MOT17-02-FRCNN/det/det.txt gt_path = '' img_folder = '/home/ma-user/modelarts/inputs/data_url_0/img1'#MOT17-02-FRCNN\img1 triplet_model = '/home/ma-user/modelarts/inputs/data_url_0/model/20211201-122017/'#train_tripletloss的结果 seq_model = '/home/ma-user/modelarts/inputs/data_url_0/model/model/model.ckpt'#train_cnn_trajectory_2d.py的结果 错误日志：
> 
> > /home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py(762)comb_cost()
> > -> comb_fea_mat[cnt,4:,t1_min-t_min:t1_max-t_min+1,0] = np.transpose(tracklet_mat['appearance_fea_mat'][cand_idx,2:])
> > (Pdb)
> > Traceback (most recent call last):
> > File "/home/ma-user/modelarts/user-job-dir/code/TC_tracker.py", line 35, in 
> > track_struct = tracklet_utils_3c.TC_tracker()
> > File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 2739, in TC_tracker
> > batch_mask_2, batch_Y, keep_prob, y_conv)
> > File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 1774, in tracklet_clustering
> > batch_mask_2, batch_Y, keep_prob, y_conv)
> > File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 1114, in get_assign_cost
> > batch_Y, keep_prob, y_conv)
> > File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 762, in comb_cost
> > comb_fea_mat[cnt,4:,t1_min-t_min:t1_max-t_min+1,0] = np.transpose(tracklet_mat['appearance_fea_mat'][cand_idx,2:])
> > File "/home/ma-user/modelarts/user-job-dir/code/tracklet_utils_3c.py", line 762, in comb_cost
> > comb_fea_mat[cnt,4:,t1_min-t_min:t1_max-t_min+1,0] = np.transpose(tracklet_mat['appearance_fea_mat'][cand_idx,2:])
> > File "/home/ma-user/anaconda/lib/python3.7/bdb.py", line 88, in trace_dispatch
> > return self.dispatch_line(frame)
> > File "/home/ma-user/anaconda/lib/python3.7/bdb.py", line 113, in dispatch_line
> > if self.quitting: raise BdbQuit
> > bdb.BdbQuit
> > 问题：我做错了什么吗？为什么会报这个错？

我已经在det.txt首添加了一行空行
