### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by P3ngLiu** [GaoangW/TNT#8]
When i try to test one of the AIcity track 1 video using your pretrained model, i got this error. Is it because of the Python or tensorflow version? Since i'm using the latest version, not as you metioned in the Github.

Model directory: D:/UAlbany/Master Project/AIcity/AI_city_model
W1021 23:36:58.552373 18184 deprecation_wrapper.py:119] From D:\Github\TNT\AIC19\facenet.py:381: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.
Metagraph file: model-20181126-234950.meta

Checkpoint file: model-20181126-234950.ckpt-29267
2019-10-21 23:37:00.305005: W tensorflow/core/graph/graph_constructor.cc:1352] Importing a graph with a lower producer version 26 into an existing graph with producer version 38. Shape inference will have run different parts of the graph with different producer versions.
Traceback (most recent call last):
  File "D:/Github/TNT/AIC19/TC_tracker.py", line 37, in <module>
    track_struct = tracklet_utils_3c.TC_tracker()
  File "D:\Github\TNT\AIC19\tracklet_utils_3c.py", line 2713, in TC_tracker
    crop_det_folder, triplet_model)
  File "D:\Github\TNT\AIC19\tracklet_utils_3c.py", line 2158, in feature_extract
    facenet.load_model(triplet_model, input_map=input_map)
  File "D:\Github\TNT\AIC19\facenet.py", line 381, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file), input_map=input_map)
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1449, in import_meta_graph
    **kwargs)[0]
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 928, in import_scoped_meta_graph_with_return_elements
    proto, import_scope=scope_to_prepend_to_names))
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1677, in from_proto
    ret = CondContext(context_def=context_def, import_scope=import_scope)
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1586, in __init__
    self._init_from_proto(context_def, import_scope=import_scope)
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1618, in _init_from_proto
    values_def=context_def.values_def, import_scope=import_scope)
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1388, in __init__
    self._init_values_from_proto(values_def, import_scope=import_scope)
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1420, in _init_values_from_proto
    g.as_graph_element(op)._set_control_flow_context(self)
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3796, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\benny\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3856, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'decode_image/cond_jpeg/is_png' refers to an Operation not in the graph."

**Comment by P3ngLiu** [comment]
Ok, it is solved. The error is caused by the Tensorflow version. Add this line: 
with tf.name_scope("tempscope"):   in the create_input_pipeline function in facenet.py can fix it.
